# 服务器端口
server:
  port: 8009



# 服务名
spring:
  application:
    name: service-acl
  # nacos服务地址
  #spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.79.131:8848


  # 环境设置 : dev、test、prod
#  profiles:
#    active: dev

    #数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.79.131:3306/gulimall_admin?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  #redis配置
  redis:
    host: 192.168.79.131
    port: 6379
    Auth: requirepass
#    password: requirepass
#    timeout: 180000

  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mapper-locations: classpath:/mapper/xml/*.xml

#开启熔断机制
#feign:
#  hystrix:
#    enabled: true

#设置hystrix 超时时间 默认1000ms

